kitty_mod alt+shift

font_family      Hack
bold_font        Hack Bold
italic_font      Hack Italic
bold_italic_font Hack Bold Italic

font_size 8.0

adjust_line_height  110%
adjust_column_width 105%

disable_ligatures never

cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval -1

cursor_stop_blinking_after 15.0

strip_trailing_spaces smart
select_by_word_characters -._~?&=%+#

focus_follows_mouse yes
remember_window_size  no

window_padding_width 0

foreground #dddddd
background #2e3440

clipboard_control write-clipboard write-primary read-clipboard read-primary


map alt+shift+j scroll_line_down
map alt+shift+k scroll_line_up

map alt+shift+h scroll_page_down
map alt+shift+l scroll_page_up

map alt+shift+, scroll_home
map alt+shift+. scroll_end

map alt+shift+enter show_scrollback

# open url
map ctrl+shift+e kitten hints

# open selected path
map ctrl+shift+p>shift+f kitten hints --type path
# insert selected path
map ctrl+shift+p>f kitten hints --type path --program -
# insert selected line
map ctrl+shift+p>l kitten hints --type line --program -
# insert selected word
map ctrl+shift+p>w kitten hints --type word --program -
# insert selected hash
map ctrl+shift+p>h kitten hints --type hash --program -